name: "Build Android app"

on:
  push:
    branches: [main]
    # can add push and pull_request here 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Yarn Install
        run: |
             yarn install  

      - name: Build application
        run: |
             cd ./android &&
             ./gradlew assembleRelease  
             
      - name: Upload Release Build to Artifacts
        uses: actions/upload-artifact@v3
        with:
           name: release-artifacts.apk
           path: |
            android/app/build/outputs/apk/release/
            retention-days: 3
             
    #   - name: Create Github Release
    #     uses: softprops/action-gh-release@v1

    #     env:
    #      GITHUB_TOKEN: ${{secrets.TOKEN_HUB_RELEASE}}
